# bundler.py
# Place in root of LoadstringIris, then run: python bundler.py

import os
import re

# Exact load order — dependencies before dependents
# lib/widgets/init.lua loads all widget submodules, so it goes last in widgets
FILES = [
    "lib/PubTypes.lua",
    "lib/Types.lua",
    "lib/WidgetTypes.lua",
    "lib/config.lua",
    "lib/Internal.lua",
    "lib/API.lua",
    "lib/widgets/Root.lua",
    "lib/widgets/Window.lua",
    "lib/widgets/Menu.lua",
    "lib/widgets/Format.lua",
    "lib/widgets/Text.lua",
    "lib/widgets/Button.lua",
    "lib/widgets/Checkbox.lua",
    "lib/widgets/RadioButton.lua",
    "lib/widgets/Input.lua",
    "lib/widgets/Combo.lua",
    "lib/widgets/Tree.lua",
    "lib/widgets/Table.lua",
    "lib/widgets/Tab.lua",
    "lib/widgets/Plot.lua",
    "lib/widgets/Image.lua",
    "lib/widgets/init.lua",
    "lib/demoWindow.lua",
    "lib/init.lua",
]

def path_to_varname(path):
    # lib/widgets/Button.lua -> _iris_widgets_Button
    # lib/init.lua           -> _iris_init
    rel = path.replace("lib/", "").replace(".lua", "").replace("/", "_")
    return "_iris_" + rel

def resolve_require(inner, current_file):
    inner = inner.strip()
    if not inner.startswith("script"):
        return None

    current_file = current_file.replace("\\", "/")
    current_dir = "/".join(current_file.split("/")[:-1])

    parts = inner.split(".")
    resolved_dir = current_dir

    i = 1
    name_parts = []
    while i < len(parts):
        part = parts[i]
        if part == "Parent":
            parent = "/".join(resolved_dir.split("/")[:-1])
            resolved_dir = parent if parent else "lib"  # ← the fix
        else:
            name_parts = parts[i:]
            break
        i += 1

    if not name_parts:
        return None

    name = "/".join(name_parts)

    candidates = [
        f"{resolved_dir}/{name}.lua",
        f"{resolved_dir}/{name}/init.lua",
    ]

    for c in candidates:
        parts_c = []
        for seg in c.split("/"):
            if seg == "..":
                if parts_c: parts_c.pop()
            elif seg and seg != ".":
                parts_c.append(seg)
        normalized = "/".join(parts_c)
        if normalized in FILES:
            return path_to_varname(normalized)

    return None


def bundle():
    out = []
    out.append("-- Iris bundle generated by bundler.py")
    out.append("-- Source: https://github.com/SirMallard/Iris")
    out.append("-- Usage:  loadstring(game:HttpGet(RAW_URL))().Init(game.CoreGui)")
    out.append("-- LOCALSCRIPT CONTEXT ONLY")
    out.append("assert(game:GetService('RunService'):IsClient(), 'Iris must run on the client')")
    out.append("")
    unresolved_log = []

    for filepath in FILES:
        if not os.path.exists(filepath):
            print(f"  MISSING: {filepath}")
            continue

        varname = path_to_varname(filepath)
        print(f"  {filepath} -> {varname}")

        with open(filepath, "r", encoding="utf-8") as f:
            src = f.read()

        # Find and replace all require(...) calls
        pattern = re.compile(r'require\(([^)]+)\)')



        def replacer(match):
            inner = match.group(1)
            resolved = resolve_require(inner, filepath)
            if resolved:
                return resolved
            # Not a script.* require — leave it alone
            if inner.strip().startswith("script"):
                unresolved_log.append(f"  UNRESOLVED: require({inner}) in {filepath}")
            return match.group(0)

        patched = pattern.sub(replacer, src)

        out.append(f"-- {'─' * 60}")
        out.append(f"-- {filepath}")
        out.append(f"-- {'─' * 60}")
        out.append(f"local {varname} = (function()")
        out.append(f"    local script = {{ Name = \"{os.path.basename(filepath)}\" }}")
        for line in patched.splitlines():
            out.append("    " + line)
        out.append(f"end)()")
        out.append("")    # The init.lua module is the return value
    out.append("-- Entry point")
    out.append("return _iris_init")

    result = "\n".join(out)

    with open("iris_bundle.lua", "w", encoding="utf-8") as f:
        f.write(result)

    print("\n── Bundle written to iris_bundle.lua")

    if unresolved_log:
        print("\n── UNRESOLVED REQUIRES (fix these manually):")
        for line in unresolved_log:
            print(line)
    else:
        print("── All requires resolved cleanly")

    print("\n── Loadstring usage:")
    print('   local Iris = loadstring(game:HttpGet(RAW_URL))().Init(game.CoreGui)')

if __name__ == "__main__":
    print("── Bundling Iris...\n")
    bundle()
